### ISSUE TITLE
An unsuccessful attempt to connect.

### ISSUE THREAD

**Issue by Denis-Raev** [yourmnbbn/tiny-csgo-server#5]
When trying to connect to the Tiny server, I get the following messages. Moreover ... After that, it does not let me into the server on which the redirect occurs, exactly until I rest the CS: GO client.

Connecting to public(IP:9001) ...
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
Connecting to public(IP:27015) ...
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
#Valve_Reject_Connect_From_Lobby
**** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'PopupManager'
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_MAINMENU
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_MAINMENU
PNG load error Interlace handling should be turned on when using png_read_image

**Comment by yourmnbbn** [comment]
For information about redirecting not working please refer to [this comment](https://github.com/yourmnbbn/tiny-csgo-server/issues/4#issuecomment-1296258994)

**Comment by Denis-Raev** [comment]
> For information about redirecting not working please refer to [this comment](https://github.com/yourmnbbn/tiny-csgo-server/issues/4#issuecomment-1296258994)

That is, in principle, from under one network (with one external IP address), this will not work?
You need to bring tiny to the network with a different external IP address.
I have Proxmox VE on my server and the game server and tiny are on different VMs. You write about how this can be somehow bypassed, is there a known way?

**Comment by yourmnbbn** [comment]
It’s not about the network, it’s about csgo client is using the reservation id of the previous “proxy server” to request a connection with the target server when processing redirecting, so the requested id doesn’t match the target server id, target server will reject this connection and the error code is valve reject from lobby. 

Clients connect to LAN server don’t require reservation id, this will work with all the LAN server redirecting. 

[This sourcemod extension](https://github.com/PerfectLaugh/RejectLobbyDisabler) will be able to prevent the connection failure caused by unmatched reservation id.

**Comment by yourmnbbn** [comment]
It’s not about the network, it’s about csgo client is using the reservation id of the previous “proxy server” to request a connection with the target server when processing redirecting, so the requested id doesn’t match the target server id, target server will reject this connection and the error code is valve reject from lobby. 

Clients connect to LAN server don’t require reservation id, this will work with all the LAN server redirecting. 

[This sourcemod extension](https://github.com/PerfectLaugh/RejectLobbyDisabler) will be able to prevent the connection failure caused by unmatched reservation id.

**Comment by Denis-Raev** [comment]
> 

Thank you so much! And the last question. Where can I change the name of the server, the number of slots available / occupied and the name of the map?

As far as I understand it, using https://github.com/yourmnbbn/smext-fakequeries on a tiny server will not work for the illusion of playing players. Only this https://github.com/yourmnbbn/tiny-csgo-client or this https://github.com/yourmnbbn/tiny-csgo-client/tree/limited will work with tiny server.

**Comment by Denis-Raev** [comment]
> It’s not about the network, it’s about csgo client is using the reservation id of the previous “proxy server” to request a connection with the target server when processing redirecting, so the requested id doesn’t match the target server id, target server will reject this connection and the error code is valve reject from lobby.
> 
> Clients connect to LAN server don’t require reservation id, this will work with all the LAN server redirecting.
> 
> [This sourcemod extension](https://github.com/PerfectLaugh/RejectLobbyDisabler) will be able to prevent the connection failure caused by unmatched reservation id.

Thank you so much! And the last question. Where can I change the name of the server, the number of slots available / occupied and the name of the map?

As far as I understand it, using https://github.com/yourmnbbn/smext-fakequeries on a tiny server will not work for the illusion of playing players. Only this https://github.com/yourmnbbn/tiny-csgo-client or this https://github.com/yourmnbbn/tiny-csgo-client/tree/limited will work with tiny server.

**Comment by yourmnbbn** [comment]
Tiny server doesn’t support sourcemod add on. To fake players, you have to authenticate players, whether by using tiny client or implementation authentication yourself.

**Comment by Denis-Raev** [comment]
Everything is very clear.  Thank you so much!

**Comment by GinTR1k** [comment]
> It’s not about the network, it’s about csgo client is using the reservation id of the previous “proxy server” to request a connection with the target server when processing redirecting, so the requested id doesn’t match the target server id, target server will reject this connection and the error code is valve reject from lobby.
> 
> Clients connect to LAN server don’t require reservation id, this will work with all the LAN server redirecting.
> 
> [This sourcemod extension](https://github.com/PerfectLaugh/RejectLobbyDisabler) will be able to prevent the connection failure caused by unmatched reservation id.

Hi!

Could you explain me how to build/compile this extension? I've spent over 3 hours for research and nothing =/
